version: "3.8"
services:
  emitent:
    build: emitent-service/.
    # ports:
    #  - "3000:3000"
    depends_on:
      - db
    environment:
     MONGO: "mongodb://db:27017"
     ADDR: "0.0.0.0:3000"
  db:
    image: "mongo:latest"
  gateway:
    build: gateway/.
    ports: 
      - "8080:8080"
    depends_on:
      - emitent
  web-seed:
    build:
      context: web-seed/.
      dockerfile: Dockerfile
      args:
        API_URL: "http://localhost:8080/v1"
    ports:
      - "80:80"
    depends_on:
      - gateway
    environment:
      PORT: "80"
      