version: "3.8"
services:
  emitent:
    build: .
    ports:
     - "3000:3000"
    depends_on:
      - db
    environment:
     MONGO: "mongodb://db:27017"
     ADDR: "0.0.0.0:3000"
  db:
    image: "mongo:latest"